"""Fail-closed account permission layered over existing identity/history checks.

This file never sends, writes Sheets, calls a model, or grants permissions by
industry. Policy is operator-maintained; it must never be generated by a lead.
"""
import json
from datetime import datetime, timezone
from pathlib import Path

POLICY_PATH = Path(__file__).with_name('data') / 'contact_policy.json'


def reason(policy, company_id, company_name, website, lane, now=None):
    from workbook_sales import host, name_key
    try:
        if policy.get('enabled') is not True:
            return 'contact_policy_paused'
        account = policy['accounts'].get(company_id)
        if not account:
            return 'account_permission_missing'
        if account.get('mode') != 'BULK_ALLOWED':
            return 'account_protected_or_held'
        if not account.get('approved_by') or not account.get('approval_evidence'):
            return 'account_approval_missing'
        if not host(website) or host(account['website']) != host(website) or not name_key(company_name) or name_key(account['company_name']) != name_key(company_name):
            return 'account_identity_mismatch'
        if lane != account['lane']:
            return 'account_lane_mismatch'
        now = now or datetime.now(timezone.utc)
        expiry = datetime.fromisoformat(account['expires_at'].replace('Z', '+00:00'))
        if expiry.tzinfo is None or now >= expiry:
            return 'account_permission_expired'
        campaign = policy['campaigns'][account['campaign_id']]
        if campaign.get('enabled') is not True:
            return 'campaign_disabled'
        # Quality evidence is earned through a bounded pilot. Named accounts,
        # existing history locks and explicit permission still apply to each send.
        pilot_accounts = [a for a in policy['accounts'].values()
                          if a.get('campaign_id') == account['campaign_id'] and a.get('mode') == 'BULK_ALLOWED']
        pilot = campaign.get('mode') == 'PILOT' and 1 <= len(pilot_accounts) <= 10
        if not pilot and (campaign.get('quality_passed') is not True or not campaign.get('quality_evidence')):
            return 'campaign_quality_unapproved'
        return ''
    except (KeyError, TypeError, ValueError, AttributeError):
        return 'contact_policy_invalid'


def block_reason(company_id, company_name, website, lane):
    try:
        policy = json.loads(POLICY_PATH.read_text(encoding='utf-8'))
    except (OSError, ValueError):
        return 'contact_policy_unavailable'
    return reason(policy, company_id, company_name, website, lane)
